springfox:
  documentation:
    swagger-ui:
      path: /documentation
server:
  port : 5005
  error:
    include-message: always
    whitelabel:
      enabled: true
spring:
  database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false